### ISSUE TITLE
build pyactivemq-0.1.0 error   cms/Startable.h: No such file or directory

### ISSUE THREAD

**Issue by GoogleCodeExporter** [LernaeanHydra/pyactivemq#35]
```
What steps will reproduce the problem?
1. build the module
2.
3.

What is the expected output? What do you see instead?
[root@castestclient pyactivemq-0.1.0]# /home//xmsong/python2.5.4/bin/python 
setup.py build
running build
running build_ext
building 'pyactivemq' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O3 -Wall 
-Wstrict-prototypes -fPIC -DBOOST_PYTHON_NO_PY_SIGNATURES=1 
-DPYACTIVEMQ_ENABLE_DOCSTRINGS=0 
-I/opt/activemq-cpp-2.2.1/include/activemq-cpp-2.2.1 
-I/home/xmsong/python2.5.4/include/python2.5 -c src/main/pyactivemq.cpp -o 
build/temp.linux-x86_64-2.5/src/main/pyactivemq.o
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for 
Ada/C/ObjC but not for C++
src/main/pyactivemq.cpp:27:27: error: cms/Startable.h: No such file or directory
src/main/pyactivemq.cpp:28:27: error: cms/Stoppable.h: No such file or directory
src/main/pyactivemq.cpp:29:27: error: cms/Closeable.h: No such file or directory
src/main/pyactivemq.cpp:30:30: error: cms/DeliveryMode.h: No such file or 
directory
src/main/pyactivemq.cpp:34: error: ‘cms’ has not been declared
src/main/pyactivemq.cpp:35: error: ‘cms’ has not been declared
src/main/pyactivemq.cpp:36: error: ‘cms’ has not been declared
src/main/pyactivemq.cpp: In constructor 
‘std_vector_to_tuple<T>::std_vector_to_tuple()’:
src/main/pyactivemq.cpp:59: error: ‘vector’ is not a member of ‘std’
src/main/pyactivemq.cpp:59: error: ‘vector’ is not a member of ‘std’
src/main/pyactivemq.cpp:59: error: wrong number of template arguments (1, 
should be 2)
/usr/include/boost/python/to_python_converter.hpp:17: error: provided for 
‘template<class T, class Conversion> struct 
boost::python::to_python_converter’
src/main/pyactivemq.cpp:59: error: expected unqualified-id before ‘,’ token
src/main/pyactivemq.cpp:59: error: ‘vector’ is not a member of ‘std’
src/main/pyactivemq.cpp:59: error: ‘vector’ is not a member of ‘std’
src/main/pyactivemq.cpp:59: error: template argument 1 is invalid
src/main/pyactivemq.cpp: In function ‘void init_module_pyactivemq()’:
src/main/pyactivemq.cpp:115: error: ‘Startable’ was not declared in this 
scope
src/main/pyactivemq.cpp:115: error: template argument 1 is invalid
src/main/pyactivemq.cpp:116: error: ‘Startable’ is not a class or namespace
src/main/pyactivemq.cpp:119: error: ‘Stoppable’ was not declared in this 
scope
src/main/pyactivemq.cpp:119: error: template argument 1 is invalid
src/main/pyactivemq.cpp:120: error: ‘Stoppable’ is not a class or namespace
src/main/pyactivemq.cpp:123: error: ‘Closeable’ was not declared in this 
scope
src/main/pyactivemq.cpp:123: error: template argument 1 is invalid
src/main/pyactivemq.cpp:124: error: ‘Closeable’ is not a class or namespace
src/main/pyactivemq.cpp:144: error: ‘cms’ was not declared in this scope
src/main/pyactivemq.cpp:144: error: template argument 1 is invalid
src/main/pyactivemq.cpp:147: error: ‘cms’ is not a class or namespace
src/main/pyactivemq.cpp:149: error: ‘cms’ is not a class or namespace
src/main/pyactivemq.cpp: At global scope:
src/main/pyactivemq.cpp:78: warning: ‘pyactivemq_docstring’ defined but not 
used
error: command 'gcc' failed with exit status 1
[root@castestclient pyactivemq-0.1.0]# 
[root@castestclient pyactivemq-0.1.0]# 
[root@castestclient pyactivemq-0.1.0]# ls
build  CHANGES.txt  LICENSE.txt  MANIFEST  PKG-INFO  setup.cfg  setup.py  src  
win_build

What version of the product are you using? On what operating system?
[root@castestclient examples]# arch
x86_64
[root@castestclient examples]# cat /etc/issue
CentOS release 5.3 (Final)
Kernel \r on an \m

[root@castestclient examples]# /home/xmsong/python2.5.4/bin/python -V
Python 2.5.4
[root@castestclient examples]# 

pyactivemq-0.1.0

Please provide any additional information below.
 cms/Startable.h: No such file or directory
```

Original issue reported on code.google.com by `JimmySo...@gmail.com` on 11 Oct 2010 at 2:37

**Comment by GoogleCodeExporter** [comment]
```
when i build with pyactivemq-0.1.0.tar.gz ,error information show as above.
```

Original comment by `JimmySo...@gmail.com` on 11 Oct 2010 at 5:23

**Comment by GoogleCodeExporter** [comment]
```
[root@castestclient pyactivemq-0.1.0]# /home//xmsong/python2.5.4/bin/python 
setup.py build
running build
running build_ext
building 'pyactivemq' extension
creating build
creating build/temp.linux-x86_64-2.5
creating build/temp.linux-x86_64-2.5/src
creating build/temp.linux-x86_64-2.5/src/main
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O3 -Wall 
-Wstrict-prototypes -fPIC -DBOOST_PYTHON_NO_PY_SIGNATURES=1 
-DPYACTIVEMQ_ENABLE_DOCSTRINGS=0 
-I/opt/activemq-cpp-2.2.1/include/activemq-cpp-2.2.1 
-I/home/xmsong/python2.5.4/include/python2.5 -c src/main/pyactivemq.cpp -o 
build/temp.linux-x86_64-2.5/src/main/pyactivemq.o
cc1plus: warning: command line option "-Wstrict-prototypes" is valid for 
Ada/C/ObjC but not for C++
src/main/pyactivemq.cpp:27:27: error: cms/Startable.h: No such file or directory
src/main/pyactivemq.cpp:28:27: error: cms/Stoppable.h: No such file or directory
src/main/pyactivemq.cpp:29:27: error: cms/Closeable.h: No such file or directory
src/main/pyactivemq.cpp:30:30: error: cms/DeliveryMode.h: No such file or 
directory
src/main/pyactivemq.cpp:34: error: ‘cms’ has not been declared
src/main/pyactivemq.cpp:35: error: ‘cms’ has not been declared
src/main/pyactivemq.cpp:36: error: ‘cms’ has not been declared
src/main/pyactivemq.cpp: In constructor 
‘std_vector_to_tuple<T>::std_vector_to_tuple()’:
src/main/pyactivemq.cpp:59: error: ‘vector’ is not a member of ‘std’
src/main/pyactivemq.cpp:59: error: ‘vector’ is not a member of ‘std’
src/main/pyactivemq.cpp:59: error: wrong number of template arguments (1, 
should be 2)
/usr/include/boost/python/to_python_converter.hpp:17: error: provided for 
‘template<class T, class Conversion> struct 
boost::python::to_python_converter’
src/main/pyactivemq.cpp:59: error: expected unqualified-id before ‘,’ token
src/main/pyactivemq.cpp:59: error: ‘vector’ is not a member of ‘std’
src/main/pyactivemq.cpp:59: error: ‘vector’ is not a member of ‘std’
src/main/pyactivemq.cpp:59: error: template argument 1 is invalid
src/main/pyactivemq.cpp: In function ‘void init_module_pyactivemq()’:
src/main/pyactivemq.cpp:115: error: ‘Startable’ was not declared in this 
scope
src/main/pyactivemq.cpp:115: error: template argument 1 is invalid
src/main/pyactivemq.cpp:116: error: ‘Startable’ is not a class or namespace
src/main/pyactivemq.cpp:119: error: ‘Stoppable’ was not declared in this 
scope
src/main/pyactivemq.cpp:119: error: template argument 1 is invalid
src/main/pyactivemq.cpp:120: error: ‘Stoppable’ is not a class or namespace
src/main/pyactivemq.cpp:123: error: ‘Closeable’ was not declared in this 
scope
src/main/pyactivemq.cpp:123: error: template argument 1 is invalid
src/main/pyactivemq.cpp:124: error: ‘Closeable’ is not a class or namespace
src/main/pyactivemq.cpp:144: error: ‘cms’ was not declared in this scope
src/main/pyactivemq.cpp:144: error: template argument 1 is invalid
src/main/pyactivemq.cpp:147: error: ‘cms’ is not a class or namespace
src/main/pyactivemq.cpp:149: error: ‘cms’ is not a class or namespace
src/main/pyactivemq.cpp: At global scope:
src/main/pyactivemq.cpp:78: warning: ‘pyactivemq_docstring’ defined but not 
used
error: command 'gcc' failed with exit status 1
[root@castestclient pyactivemq-0.1.0]# 
when i try  pyactivemq-0.1.0.zip，the same error information show
```

Original comment by `JimmySo...@gmail.com` on 11 Oct 2010 at 5:24

**Comment by GoogleCodeExporter** [comment]
```
Hello,

Unfortunately, pyactivemq hasn't been updated for AMQCPP 3+ yet.

Timothy Bish was going to take over to handle that, but I don't think he's had 
time yet.

Cheers

Albert
```

Original comment by `fullung@gmail.com` on 11 Oct 2010 at 6:06
- Added labels: **Priority-Critical**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
Thanks~
```

Original comment by `JimmySo...@gmail.com` on 12 Oct 2010 at 12:45
